Create post
yongsokhengkhmer/ruby-thesis pull request #17
Opened 2016-10-06 03:49 UTC by NgengChhengkim

2016-10-06 15:28 UTC, yongsokheng commented on app/controllers/posts_controller.rb
> +  def create
load cancancan

2016-10-06 15:32 UTC, yongsokheng commented on app/controllers/posts_controller.rb
> +      current_user.activities.create trackable_id: @post.id, trackable_type: @post.class.name
@post.create_activity user_id: current_user.id

2016-10-06 15:34 UTC, yongsokheng commented on app/controllers/static_pages_controller.rb
> +    @job_types = JobType.all.limit(10)
Settings

2016-10-06 15:38 UTC, yongsokheng commented on app/models/job_post.rb
> +  def job_post_error
dung lam gi?

2016-10-06 15:38 UTC, yongsokheng commented on app/models/job_post.rb
> +     errors.add(:base, "content blank") if post.content.blank?
dung lam gi?

2016-10-06 15:39 UTC, yongsokheng commented on app/models/post.rb
> +  accepts_nested_attributes_for :job_post, allow_destroy: true
allow_destroy?

2016-10-06 15:46 UTC, yongsokheng commented on app/models/share_post.rb
> +  has_one :activities, as: :trackable, dependent: :destroy
has_one :activity, as: :trackable, dependent: :destroy

2016-10-06 15:47 UTC, NgengChhengkim commented on app/controllers/static_pages_controller.rb
> +    @job_types = JobType.all
se lam trong pull khac. pull selectize data

2016-10-06 15:48 UTC, yongsokheng commented on app/controllers/static_pages_controller.rb
> +    @job_types = JobType.all
OK

2016-10-06 15:55 UTC, yongsokheng commented on app/views/posts/_job_post_form.html.erb
> +<%= form_for Post.new, url: posts_path, method: :post, remote: true,
Post.new de trong controller

2016-10-06 15:58 UTC, yongsokheng commented on app/views/posts/_job_post_form.html.erb
> +  <%= f.fields_for :job_post, f.object.build_job_post do |builder| %>
build_job_post viet knong controller . knong neng ot cham bach viet ey te

2016-10-06 16:01 UTC, yongsokheng commented on app/views/posts/_job_post_form.html.erb
> +    <div><%= f.text_area :content, id: "post-content" %></div>
min bach dak height knong css te, sak brer rows cheng merl der ot
`f.text_area :content, rows: 2`

2016-10-06 16:03 UTC, yongsokheng commented on app/views/posts/_job_post_form.html.erb
> +      <input type="file" style="display: none;" name="post[image]" id="post_image">
`f.object.file :post_image`

2016-10-06 16:05 UTC, yongsokheng commented on app/views/posts/_post_form.html.erb
> +<%= form_for :post, url: posts_path, method: :post, remote: true, html: {id: "new-post"} do |f| %>
nhu tren

2016-10-06 16:05 UTC, yongsokheng commented on app/views/posts/_post_form.html.erb
> +      <input type="file" style="display: none;" name="post[image]" id="post_image">
nhu tren

2016-10-06 16:05 UTC, yongsokheng commented on app/views/posts/_post_form.html.erb
> +  <div class="button">
doch khnea, brer partial tov

2016-10-06 16:54 UTC, NgengChhengkim commented on app/views/posts/_job_post_form.html.erb
> +    <div><%= f.text_area :content, id: "post-content" %></div>
ort der te

2016-10-08 09:19 UTC, yongsokheng commented on app/models/education.rb
> +  validates_uniqueness_of :degree_id, scope: :user_id
pull neng mech tak tong with education.rb ?

2016-10-08 09:21 UTC, yongsokheng commented on app/views/posts/_button.erb
> +<div class="button">
app/views/posts/_button.html.erb

2016-10-08 09:22 UTC, yongsokheng commented on app/views/posts/_button.erb
> +    <input type="file" style="display: none;" name="post[image]" id="post_image">
brer f.file :image ot ket te?

2016-10-08 09:23 UTC, yongsokheng commented on app/views/posts/_job_post_form.html.erb
> +    <div><%= f.text_area :content, id: "post-content" %></div>
f.text_area :content, size: "30x10"

2016-10-08 09:27 UTC, yongsokheng commented on app/views/posts/create.js.erb
> +    $("#post-errors").html("<div class='text-danger'><%= t 'posts.post_error' %></div>");
```
error_element = $("#post-errors");
else
error_element = $("#job-post-errors")
...
error_element.html("<div class='text-danger'><%= t 'posts.job_post_error' %></div>");
```

2016-10-08 09:29 UTC, NgengChhengkim commented on app/views/posts/_job_post_form.html.erb
> +    <div><%= f.text_area :content, id: "post-content" %></div>
mech ban ort dak css.

2016-10-08 09:29 UTC, NgengChhengkim commented on app/views/posts/_job_post_form.html.erb
> +    <div><%= f.text_area :content, id: "post-content" %></div>
?

2016-10-08 09:30 UTC, yongsokheng commented on app/views/posts/_button.html.erb
> +    <input type="file" style="display: none;" name="post[image]" id="post_image">
brer input file bos rail ot ket te?

2016-10-08 09:31 UTC, yongsokheng commented on app/views/posts/_job_post_form.html.erb
> +    <div><%= f.text_area :content, id: "post-content" %></div>
dak cheng sruol merl cheang :smile:

2016-10-08 09:42 UTC, NgengChhengkim commented on app/views/posts/_button.html.erb
> +    <input type="file" style="display: none;" name="post[image]" id="post_image">
brer file_field  dak class form-control chol ort skal

2016-10-08 09:42 UTC, NgengChhengkim commented on app/views/posts/_job_post_form.html.erb
> +    <div><%= f.text_area :content, id: "post-content" %></div>
cheng ey pseng teat dak neng tang os mong. kchil brer css

2016-10-08 09:43 UTC, NgengChhengkim commented on app/views/posts/create.js.erb
> +    $("#post-errors").html("<div class='text-danger'><%= t 'posts.post_error' %></div>");
error pseng knea

2016-10-08 09:44 UTC, yongsokheng commented on app/views/posts/_button.html.erb
> +    <input type="file" style="display: none;" name="post[image]" id="post_image">
cheng kor ban cheng

2016-10-08 09:45 UTC, yongsokheng requested changes

2016-10-08 09:45 UTC, yongsokheng commented on app/views/posts/_job_post_form.html.erb
> +    <div><%= f.text_area :content, id: "post-content" %></div>
OK

2016-10-08 09:46 UTC, yongsokheng commented on app/views/posts/create.js.erb
> +    $("#post-errors").html("<div class='text-danger'><%= t 'posts.post_error' %></div>");
OK

2016-10-08 09:50 UTC, NgengChhengkim commented on app/views/posts/_button.html.erb
> +    <input type="file" style="display: none;" name="post[image]" id="post_image">
btn btn-default

2016-10-08 09:51 UTC, yongsokheng commented on app/models/education.rb
> +  validates_uniqueness_of :degree_id, scope: :user_id
not yet reply ??

2016-10-08 09:52 UTC, yongsokheng commented on app/views/posts/_button.html.erb
> +    <input type="file" style="display: none;" name="post[image]" id="post_image">
ok

2016-10-08 10:02 UTC, yongsokheng approved these changes

2016-10-09 07:29 UTC, merged